# Generated by Django 5.0.6 on 2024-07-22 11:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Category Title')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category_background', models.ImageField(blank=True, default=None, null=True, upload_to='category_background_images/', verbose_name='Background')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Review Title')),
                ('slug', models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Slug must be at least 5 characters long'), django.core.validators.MaxLengthValidator(100, message='Slug must be at most 100 characters long')])),
                ('description', models.TextField(blank=True, verbose_name='Review Description')),
                ('main_image', models.ImageField(blank=True, default=None, null=True, upload_to='review_main_images/', verbose_name='Main Image')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('is_published', models.BooleanField(choices=[(False, 'Draft'), (True, 'Published')], default=True, verbose_name='Status')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review.category')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
