# Generated by Django 5.0.6 on 2024-10-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_reviewtopic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewtopic',
            old_name='title',
            new_name='review_topic_title',
        ),
    ]
