# Generated by Django 5.0.6 on 2024-11-20 09:11

import review.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_rename_title_reviewtopic_review_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='review_main_images/', validators=[review.services.validate_image_size], verbose_name='Main Image'),
        ),
    ]
