# Generated by Django 5.0.6 on 2024-11-20 09:15

import review.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=review.services.get_path_for_uploading_review_main_image, validators=[review.services.validate_image_size], verbose_name='Main Image'),
        ),
    ]
